run:
	python3 InventoryAllocator/inventory_allocator.py

test:
	python3 -m unittest unittests.py -v

.PHONY : help
help :
	@echo "run  : to run the inventory_allocator.py file"
	@echo "test : to run all unittests"